import { describe, it, expect } from 'vitest'
import { runCommitMsgNoAiCheck } from '../src/checks/commit-msg-no-ai.js'

describe('commit-msg no-ai check', () => {
  it('detecta "Claude" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('feat: refactor done by Claude')
    expect(result.passed).toBe(false)
    expect(result.matches).toHaveLength(1)
  })

  it('detecta "ChatGPT" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('fix: ChatGPT suggested this fix')
    expect(result.passed).toBe(false)
  })

  it('detecta "Copilot" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('feat: Copilot autocomplete')
    expect(result.passed).toBe(false)
  })

  it('detecta "GPT-4" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('chore: generated with GPT-4')
    expect(result.passed).toBe(false)
  })

  it('detecta "Anthropic" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('docs: Anthropic API integration')
    expect(result.passed).toBe(false)
  })

  it('detecta "OpenAI" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('feat: add OpenAI client')
    expect(result.passed).toBe(false)
  })

  it('detecta "Gemini" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('fix: Gemini response parsing')
    expect(result.passed).toBe(false)
  })

  it('detecta "DeepSeek" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('refactor: DeepSeek model update')
    expect(result.passed).toBe(false)
  })

  it('detecta "Bard" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('feat: Bard integration')
    expect(result.passed).toBe(false)
  })

  it('detecta "AI-generated" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('chore: AI-generated boilerplate')
    expect(result.passed).toBe(false)
  })

  it('detecta "ai assisted" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('feat: ai assisted refactor')
    expect(result.passed).toBe(false)
  })

  it('detecta "made by ai" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('docs: made by ai')
    expect(result.passed).toBe(false)
  })

  it('detecta "Co-Authored-By: Claude" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck(
      'feat: add login\n\nCo-Authored-By: Claude <noreply@anthropic.com>'
    )
    expect(result.passed).toBe(false)
  })

  it('detecta "BecarIA" en el mensaje', () => {
    const result = runCommitMsgNoAiCheck('feat: implemented by BecarIA')
    expect(result.passed).toBe(false)
  })

  it('pasa con un mensaje normal', () => {
    const result = runCommitMsgNoAiCheck('feat: add user authentication')
    expect(result.passed).toBe(true)
    expect(result.matches).toHaveLength(0)
  })

  it('pasa con un mensaje multilinea normal', () => {
    const result = runCommitMsgNoAiCheck(
      'fix: resolve race condition in login flow\n\nThe mutex was not being released properly.'
    )
    expect(result.passed).toBe(true)
  })

  it('detecta multiples referencias en distintas lineas', () => {
    const result = runCommitMsgNoAiCheck(
      'feat: new feature\n\nGenerated by Claude\nCo-Authored-By: GPT-4 <noreply>'
    )
    expect(result.passed).toBe(false)
    expect(result.matches.length).toBeGreaterThanOrEqual(2)
  })

  it('soporta extraPatterns', () => {
    const result = runCommitMsgNoAiCheck('feat: MyCustomBot did this', {
      extraPatterns: [/MyCustomBot/i],
    })
    expect(result.passed).toBe(false)
  })

  it('es case-insensitive', () => {
    const result = runCommitMsgNoAiCheck('feat: CLAUDE helped')
    expect(result.passed).toBe(false)
  })
})
