import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { logger } from '../utils/logger.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = resolve(__dirname, '..', '..', 'templates');

/**
 * Generates configuration files for the project.
 * Creates .env from template with placeholders.
 * CLAUDE.md and other agent guidelines are generated by @geniova/git-hooks init
 * in the setupGitHooks step, not here.
 * @param {import('../catalog/projects.js').Project} project
 * @param {string} targetDir - Absolute path to the project directory
 */
export async function generateConfig(project, targetDir) {
  generateEnvFile(project, targetDir);
}

/**
 * Generates a .env file from the template, replacing placeholders with project values.
 * @param {import('../catalog/projects.js').Project} project
 * @param {string} targetDir
 */
function generateEnvFile(project, targetDir) {
  const envPath = resolve(targetDir, '.env');

  if (existsSync(envPath)) {
    logger.warn('  .env ya existe, no se sobreescribe.');
    return;
  }

  const templatePath = resolve(TEMPLATES_DIR, 'env.template');
  let content = readFileSync(templatePath, 'utf-8');

  content = content
    .replace(/\{\{PROJECT_NAME\}\}/g, project.name)
    .replace(/\{\{FIREBASE_PROJECT\}\}/g, project.firebaseProject || 'TODO')
    .replace(/\{\{ABBREVIATION\}\}/g, project.abbreviation);

  writeFileSync(envPath, content);
  logger.info(`  Generado: ${envPath}`);
}
