/**
 * @typedef {Object} Project
 * @property {string} id - Unique project identifier
 * @property {string} name - Display name
 * @property {string} abbreviation - Short abbreviation
 * @property {string} repo - GitHub repo name (under Geniova-Technologies org)
 * @property {string} stack - Tech stack description
 * @property {string} description - Short description
 * @property {string} [firebaseProject] - Firebase project ID (if applicable)
 * @property {string[]} mcpsRequired - Required MCP IDs
 * @property {string[]} mcpsOptional - Optional MCP IDs
 */

/** @type {Project[]} */
export const PROJECTS = [
  // ── Plataforma dental (core business) ──
  {
    id: 'extranet-v2',
    name: 'Extranet V2',
    abbreviation: 'EX2',
    repo: 'extranet-v2',
    stack: 'Next, Tailwind, TypeScript',
    description: 'Portal del doctor para crear y seguir tratamientos dentales',
    firebaseProject: 'geniova-extranet',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube', 'karajan'],
  },
  {
    id: 'intranet',
    name: 'Intranet',
    abbreviation: 'NTR',
    repo: 'intranet',
    stack: 'Next, Tailwind, Firebase, TypeScript',
    description: 'Produccion y seguimiento interno de tratamientos',
    firebaseProject: 'geniova-intranet',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube', 'karajan'],
  },
  {
    id: 'intranet-extended',
    name: 'Intranet-Extended',
    abbreviation: 'IEX',
    repo: 'intranet-extended',
    stack: 'Next, Firebase, JavaScript',
    description: 'Intranet para externos (digital/impresion externa)',
    firebaseProject: 'geniova-intranet-extended',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube', 'karajan'],
  },
  {
    id: 'visor-editor',
    name: 'Visor-Editor',
    abbreviation: 'VSR',
    repo: 'visor-editor',
    stack: 'Next, Three.js, JavaScript',
    description: 'Visualizacion y edicion 3D de tratamientos dentales',
    firebaseProject: 'geniova-visor',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube'],
  },
  {
    id: 'cinema4d',
    name: 'Cinema4D',
    abbreviation: 'C4D',
    repo: 'cinema4d',
    stack: 'Python',
    description: 'Diseno 3D automatizado para tratamientos',
    firebaseProject: undefined,
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['sonarqube'],
  },
  {
    id: 'geniova-platform',
    name: 'Geniova Platform',
    abbreviation: 'PLT',
    repo: 'geniova-platform',
    stack: 'Astro, Lit, Firebase, JS',
    description: 'Plataforma completa (Extranet+Intranet+DB+S3+Bot)',
    firebaseProject: 'geniova-platform',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube', 'karajan'],
  },

  // ── Herramientas internas ──
  {
    id: 'planning-game',
    name: 'PlanningGame',
    abbreviation: 'PLN',
    repo: 'planning-game',
    stack: 'Astro, Lit, Firebase, JS',
    description: 'App web de gestion de proyectos XP',
    firebaseProject: 'planning-gamexp',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube'],
  },
  {
    id: 'planning-game-mcp',
    name: 'Planning Game MCP',
    abbreviation: 'PMC',
    repo: 'planning-game-mcp',
    stack: 'Node.js, MCP SDK, Firebase, Vitest',
    description: 'MCP Server para integracion con LLMs',
    firebaseProject: 'planning-gamexp',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['sonarqube'],
  },
  {
    id: 'portal-incidencias',
    name: 'Portal de Incidencias',
    abbreviation: 'PRT',
    repo: 'portal-incidencias',
    stack: 'Astro, Lit, Firebase, JS',
    description: 'Gestion de incidencias internas y de doctores',
    firebaseProject: 'geniova-incidencias',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube'],
  },
  {
    id: 'auth-sign',
    name: 'Auth&Sign',
    abbreviation: 'A&S',
    repo: 'geniova-auth',
    stack: 'Astro, Lit, Firebase, JS',
    description: 'Login unico (user/pass y Microsoft)',
    firebaseProject: 'geniova-auth',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube'],
  },
  {
    id: 'inventario',
    name: 'Inventario',
    abbreviation: 'NVN',
    repo: 'geniova-inventario',
    stack: 'Astro, Lit, Firebase, JS',
    description: 'Inventario Geniova',
    firebaseProject: 'geniova-inventario',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube'],
  },
  {
    id: 'geniova-space',
    name: 'Geniova Space',
    abbreviation: 'GSP',
    repo: 'geniova-space',
    stack: 'Astro, Lit, Firebase, JS',
    description: 'Reserva de mesas calientes y salas',
    firebaseProject: 'geniova-space',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube'],
  },
  {
    id: 'geniova-link',
    name: 'Geniova Link',
    abbreviation: 'GNL',
    repo: 'geniova-link',
    stack: 'Astro, Lit, JS',
    description: 'Portal de links de portales y plataformas',
    firebaseProject: undefined,
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube'],
  },
  {
    id: 'firestore-myadmin',
    name: 'Firestore-Myadmin',
    abbreviation: 'FMA',
    repo: 'firestore-myadmin',
    stack: 'Lit, Web Components, Firebase',
    description: 'Gestor multi-proyecto de Firestore (estilo PHPMyAdmin)',
    firebaseProject: 'firestore-myadmin',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube'],
  },
  {
    id: 'web-geniova',
    name: 'Web Geniova',
    abbreviation: 'WGN',
    repo: 'web-geniova',
    stack: 'WordPress, Lit, Vite, PHP',
    description: 'Web corporativa',
    firebaseProject: undefined,
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube'],
  },

  // ── Gestion y soporte ──
  {
    id: 'geniova-employee',
    name: 'Geniova Employee',
    abbreviation: 'GEM',
    repo: 'geniova-employee',
    stack: 'Astro, Lit, Firebase, JS',
    description: 'Aplicacion de gestion de RRHH interna',
    firebaseProject: 'geniova-employee',
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['chrome-devtools', 'sonarqube', 'karajan'],
  },
  {
    id: 'geniova-kit',
    name: 'Geniova Kit',
    abbreviation: 'GKT',
    repo: 'geniova-kit',
    stack: 'Node.js, ESM, JS',
    description: 'Wizard de configuracion del entorno de desarrollo',
    firebaseProject: undefined,
    mcpsRequired: ['planning-game'],
    mcpsOptional: ['sonarqube'],
  },
];
