/**
 * Patrones de referencia a IA que deben bloquearse en commits.
 * Case-insensitive matching.
 */
export const AI_PATTERNS = [
  /\bClaude\b/i,
  /\bGPT[-\s]?\d*/i,
  /\bChatGPT\b/i,
  /\bCopilot\b/i,
  /\bAnthropic\b/i,
  /\bOpenAI\b/i,
  /\bGemini\b/i,
  /\bDeepSeek\b/i,
  /\bAI[- ]generated\b/i,
  /\bgenerated by AI\b/i,
  /\bgenerated by an? AI\b/i,
  /Co-Authored-By:.*\b(Claude|GPT|Copilot|Gemini|DeepSeek)\b/i,
  /\bBecarIA\b/,
]

/**
 * Archivos excluidos del check de referencias a IA.
 * Soporta glob-like matching simple.
 */
export const AI_REFS_EXCLUDED_FILES = [
  'CLAUDE.md',
  '.claude/',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  '.githooksrc.json',
]

/**
 * Extensiones de archivos que se lintean.
 */
export const LINTABLE_EXTENSIONS = {
  eslint: ['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsx', '.tsx', '.astro'],
  stylelint: ['.css', '.scss', '.less'],
}

/**
 * Extensiones de archivos a analizar para regresiones.
 */
export const REGRESSION_EXTENSIONS = [
  '.js', '.mjs', '.cjs', '.ts', '.mts', '.cts',
  '.jsx', '.tsx', '.astro',
  '.css', '.scss', '.less',
  '.html', '.json',
]

/**
 * Archivos/directorios excluidos del análisis.
 */
export const EXCLUDED_PATHS = [
  'node_modules/',
  'dist/',
  'build/',
  '.firebase/',
  'coverage/',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
]
